### ISSUE TITLE
Cannot authenticate with username and password

### ISSUE THREAD

**Issue by betamaxed** [HumanSignal/label-studio-sdk#134]
Repro steps:
```python
url = "http://localhost:8080"
username = "myusername"
password = "mypassword"
creds = label_studio_sdk.client.ClientCredentials(email=username, password=password)
client = label_studio_sdk.Client(url, None, credentials=creds)
```

Expected result:
Client is created without issue.

Actual result:
AttributeError: 'Client' object has no attribute 'cookies'

Underlying issue:
https://github.com/heartexlabs/label-studio-sdk/blob/c3f77cd82c3c9577696c801c498c72b45b24415c/label_studio_sdk/client.py#LL94C14-L94C21

`self.cookies` is referenced before it is initialized.

**Comment by jombooth** [comment]
looks like this was fixed in #135 which has now been merged (thanks, @betamaxed!). Please reopen if there are still issues with creating the client.
